/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vektorel.gui;

/**
 *
 * @author metin
 */
public class frmMoment extends javax.swing.JFrame {


    private String cum1;
   

    public String getCum1() {
        return cum1;
    }

    public void setCum1(String cum1) {
        this.cum1 = cum1;
    }

    
    
    public frmMoment() {
        initComponents();
        setCum1("Energy ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        relaxbtn = new javax.swing.JButton();
        energybtn = new javax.swing.JButton();
        sleepbtn = new javax.swing.JButton();
        focusbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        relaxbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        relaxbtn.setText("Relax");
        relaxbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relaxbtnActionPerformed(evt);
            }
        });

        energybtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        energybtn.setText("Energy");
        energybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                energybtnActionPerformed(evt);
            }
        });

        sleepbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sleepbtn.setText("Sleep");
        sleepbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleepbtnActionPerformed(evt);
            }
        });

        focusbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        focusbtn.setText("Focus");
        focusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                focusbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(focusbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(sleepbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(relaxbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(energybtn)))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(relaxbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(energybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sleepbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(focusbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void energybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_energybtnActionPerformed
        setCum1("Energy ");
        frmChooseATool frm = new frmChooseATool();
        frm.setVisible(true);
    }//GEN-LAST:event_energybtnActionPerformed

    private void relaxbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relaxbtnActionPerformed
        setCum1("Relax ");
        frmChooseATool frm = new frmChooseATool();
        frm.setVisible(true);
    }//GEN-LAST:event_relaxbtnActionPerformed

    private void sleepbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sleepbtnActionPerformed
        setCum1("Sleep ");
        frmChooseATool frm = new frmChooseATool();
        frm.setVisible(true);
    }//GEN-LAST:event_sleepbtnActionPerformed

    private void focusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_focusbtnActionPerformed
        setCum1("Focus ");
        frmChooseATool frm = new frmChooseATool();
        frm.setVisible(true);
    }//GEN-LAST:event_focusbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMoment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMoment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMoment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMoment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMoment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton energybtn;
    private javax.swing.JButton focusbtn;
    private javax.swing.JButton relaxbtn;
    private javax.swing.JButton sleepbtn;
    // End of variables declaration//GEN-END:variables
}
